spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/buses_db
  redis:
    host: redis
  rabbitmq:
    host: rabbitmq

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka