spring:
  datasource:
    url: jdbc:postgresql://postgres:5433/buses_db
  redis:
    host: redis
  rabbitmq:
    host: rabbitmq

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:BusesLkSecretKey2025VeryLongAndSecureKey}
  access-token-expiration: 3600
  refresh-token-expiration: 86400