# application.yml
server:
  port: 8083
  servlet:
    context-path: /

spring:
  application:
    name: route-service
  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5433/routes_db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
        format_sql: true
        show_sql: false
        default_schema: public
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false

  # Updated Redis configuration - use spring.data.redis instead of spring.redis
  data:
    redis:
      host: localhost
      port: 6379
      password: redis123
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  # RabbitMQ configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    virtual-host: /

  cloud:
    config:
      enabled: false
      discovery:
        enabled: false
      import-check:
        enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

jwt:
  secret: ${JWT_SECRET:BusesLkSecretKey2025VeryLongAndSecureKey}
  access-token-expiration: 3600
  refresh-token-expiration: 86400

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    lk.buses: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Cache Configuration
cache:
  routes:
    ttl: 3600
    max-size: 1000
  fares:
    ttl: 7200
    max-size: 5000
  travel-times:
    ttl: 1800
    max-size: 2000