spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:users_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres123}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:redis123}